#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
# Source0 file verified with key 0xB1DD35CCFDEB5FF3 (robin@alldunn.com)
#
Name     : pypi-wxPython
Version  : 4.2.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/d9/33/b616c7ed4742be6e0d111ca375b41379607dc7cc7ac7ff6aead7a5a0bf53/wxPython-4.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/d9/33/b616c7ed4742be6e0d111ca375b41379607dc7cc7ac7ff6aead7a5a0bf53/wxPython-4.2.0.tar.gz
Source1  : https://files.pythonhosted.org/packages/d9/33/b616c7ed4742be6e0d111ca375b41379607dc7cc7ac7ff6aead7a5a0bf53/wxPython-4.2.0.tar.gz.asc
Summary  : Cross platform GUI toolkit for Python, "Phoenix" version
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause BSL-1.0 GPL-2.0 GPL-3.0 HPND LGPL-2.0 Libpng MIT OFL-1.1 TCL Zlib libtiff wxWindows
Requires: pypi-wxPython-bin = %{version}-%{release}
Requires: pypi-wxPython-license = %{version}-%{release}
Requires: pypi-wxPython-python = %{version}-%{release}
Requires: pypi-wxPython-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : cmake
BuildRequires : doxygen-bin
BuildRequires : freeglut-dev
BuildRequires : glu-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pypi(attrdict)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-requests
BuildRequires : python3-dev
BuildRequires : sip
BuildRequires : tiff-dev
BuildRequires : wxWidgets-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
sip Extension Module
====================
The sip extension module provides support for the wx package.

%package bin
Summary: bin components for the pypi-wxPython package.
Group: Binaries
Requires: pypi-wxPython-license = %{version}-%{release}

%description bin
bin components for the pypi-wxPython package.


%package dev
Summary: dev components for the pypi-wxPython package.
Group: Development
Requires: pypi-wxPython-bin = %{version}-%{release}
Provides: pypi-wxPython-devel = %{version}-%{release}
Requires: pypi-wxPython = %{version}-%{release}

%description dev
dev components for the pypi-wxPython package.


%package license
Summary: license components for the pypi-wxPython package.
Group: Default

%description license
license components for the pypi-wxPython package.


%package python
Summary: python components for the pypi-wxPython package.
Group: Default
Requires: pypi-wxPython-python3 = %{version}-%{release}
Provides: pypi-wxpython-python

%description python
python components for the pypi-wxPython package.


%package python3
Summary: python3 components for the pypi-wxPython package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pypi-wxPython package.


%prep
%setup -q -n wxPython-4.2.0
cd %{_builddir}/wxPython-4.2.0
pushd ..
cp -a wxPython-4.2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1684855741
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-wxPython
cp %{_builddir}/wxPython-%{version}/demo/data/SIL_OPEN_FONT_LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/fa2b5c52bc6b71cbf75cf48e541569d83b22c0a3 || :
cp %{_builddir}/wxPython-%{version}/ext/nanosvg/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/f4f94babc436555d2f5992e29aacc47433fbadb4 || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/3rdparty/catch/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/3rdparty/nanosvg/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/f4f94babc436555d2f5992e29aacc47433fbadb4 || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/3rdparty/pcre/LICENCE %{buildroot}/usr/share/package-licenses/pypi-wxPython/3005b2c68faac406829c8ea56376ddcb1ed0eabb || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/3rdparty/pcre/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/pypi-wxPython/ff3ed70db4739b3c6747c7f624fe2bad70802987 || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/build/cmake/modules/cotire_test/license %{buildroot}/usr/share/package-licenses/pypi-wxPython/ece76272e705e27f0c76531aac6dd0b10820bc10 || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/docs/gpl.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/docs/wine/COPYING.LIB %{buildroot}/usr/share/package-licenses/pypi-wxPython/ec2350cf4fe9c4f97c3ee5c9046d0396672c365a || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/src/expat/expat/COPYING %{buildroot}/usr/share/package-licenses/pypi-wxPython/8623dd26727a708a49dbe6a52edb1d931d70816d || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/src/motif/mdi/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-wxPython/3f65d8e23a75d7c0a9a7b7092c9249e4f8cd2db4 || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/src/motif/xmcombo/copying.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/17e3b0eea99abffe6ac71e65627413236e0b117a || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/src/png/LICENSE %{buildroot}/usr/share/package-licenses/pypi-wxPython/fc3951ba26fe1914759f605696a1d23e3b41766f || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/src/regex/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-wxPython/9a5a0d7c8ffa82a9489acbb7f0d6947a2b1bc27f || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/src/stc/scintilla/License.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/9da27f7b263edb706105ccd68880474013b11bca || :
cp %{_builddir}/wxPython-%{version}/ext/wxWidgets/src/tiff/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-wxPython/a2f64f2a85f5fd34bda8eb713c3aad008adbb589 || :
cp %{_builddir}/wxPython-%{version}/license/gpl.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/wxPython-%{version}/license/gpl.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/wxPython-%{version}/license/lgpl.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/wxPython-%{version}/sip/siplib/LICENSE-GPL2 %{buildroot}/usr/share/package-licenses/pypi-wxPython/2136dbc93e95a70deae070e44ff6b2702ec1599c || :
cp %{_builddir}/wxPython-%{version}/sip/siplib/LICENSE-GPL3 %{buildroot}/usr/share/package-licenses/pypi-wxPython/34e9b06e7f12eaed676f57481de931ec91c6ce0a || :
cp %{_builddir}/wxPython-%{version}/wx/lib/pubsub/LICENSE_BSD_Simple.txt %{buildroot}/usr/share/package-licenses/pypi-wxPython/12d9aac371b94aee9fd5e5a9465166095d6438db || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/helpviewer
/usr/bin/img2png
/usr/bin/img2py
/usr/bin/img2xpm
/usr/bin/pycrust
/usr/bin/pyshell
/usr/bin/pyslices
/usr/bin/pyslicesshell
/usr/bin/pywxrc
/usr/bin/wxdemo
/usr/bin/wxdocs
/usr/bin/wxget

%files dev
%defattr(-,root,root,-)
/usr/lib/python3.11/site-packages/wx/include/wxPython/sip.h
/usr/lib/python3.11/site-packages/wx/include/wxPython/wxpy_api.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-wxPython/12d9aac371b94aee9fd5e5a9465166095d6438db
/usr/share/package-licenses/pypi-wxPython/17e3b0eea99abffe6ac71e65627413236e0b117a
/usr/share/package-licenses/pypi-wxPython/2136dbc93e95a70deae070e44ff6b2702ec1599c
/usr/share/package-licenses/pypi-wxPython/3005b2c68faac406829c8ea56376ddcb1ed0eabb
/usr/share/package-licenses/pypi-wxPython/34e9b06e7f12eaed676f57481de931ec91c6ce0a
/usr/share/package-licenses/pypi-wxPython/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/pypi-wxPython/3f65d8e23a75d7c0a9a7b7092c9249e4f8cd2db4
/usr/share/package-licenses/pypi-wxPython/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/pypi-wxPython/8623dd26727a708a49dbe6a52edb1d931d70816d
/usr/share/package-licenses/pypi-wxPython/9a5a0d7c8ffa82a9489acbb7f0d6947a2b1bc27f
/usr/share/package-licenses/pypi-wxPython/9da27f7b263edb706105ccd68880474013b11bca
/usr/share/package-licenses/pypi-wxPython/a2f64f2a85f5fd34bda8eb713c3aad008adbb589
/usr/share/package-licenses/pypi-wxPython/ba8966e2473a9969bdcab3dc82274c817cfd98a1
/usr/share/package-licenses/pypi-wxPython/ec2350cf4fe9c4f97c3ee5c9046d0396672c365a
/usr/share/package-licenses/pypi-wxPython/ece76272e705e27f0c76531aac6dd0b10820bc10
/usr/share/package-licenses/pypi-wxPython/f4f94babc436555d2f5992e29aacc47433fbadb4
/usr/share/package-licenses/pypi-wxPython/fa2b5c52bc6b71cbf75cf48e541569d83b22c0a3
/usr/share/package-licenses/pypi-wxPython/fc3951ba26fe1914759f605696a1d23e3b41766f
/usr/share/package-licenses/pypi-wxPython/ff3ed70db4739b3c6747c7f624fe2bad70802987

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
